using System.CodeDom.Compiler;
using System.Text;
using HKW.SourceGeneratorUtils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HKW.HKWMapper.SourceGenerator;

internal class ClassSourceWriter
{
    public static void Execute(ClassInfo classInfo)
    {
        var w = new ClassSourceWriter(classInfo);
        w.Write();
    }

    private readonly ClassInfo _classInfo;
    private readonly IndentedTextWriter _writer;

    public ClassSourceWriter(ClassInfo classInfo)
    {
        _classInfo = classInfo;
        var stringStream = new StringWriter();
        _writer = new IndentedTextWriter(stringStream);
    }

    private void Write()
    {
        _writer.WriteLine("// <auto-generated>");
        _writer.WriteLine("#nullable enable");
        //_writer.WriteLine("#pragma warning disable CS1591");
        // 添加全部引用
        //_writer.WriteLine(_classInfo.Usings);
        // 添加命名空间
        _writer.WriteLine($"namespace HKW.HKWMapper");
        _writer.WriteLine("{");
        _writer.Indent++;
        // 获取可访问性
        var accessibility = _classInfo.ClassSyntax.Modifiers.GetAccessibility();
        _writer.WriteLine(
            $"{accessibility} static class {_classInfo.ClassSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat).Replace('.', '_')}MapExtensions"
        );
        _writer.WriteLine("{");
        _writer.Indent++;

        foreach (var converter in _classInfo.MapConverters)
            _writer.WriteInfo(converter);
        foreach (var config in _classInfo.MapConfigs)
            _writer.WriteInfo(config);
        foreach (var mapTarget in _classInfo.MapTargets)
        {
            if (mapTarget.Direction.HasFlag(MapDirections.To))
                _writer.WriteInfo(mapTarget.MapToMethod);
            if (mapTarget.Direction.HasFlag(MapDirections.From))
                _writer.WriteInfo(mapTarget.MapFromMethod);
        }

        _writer.Indent--;
        _writer.WriteLine();
        _writer.WriteLine("}");
        _writer.Indent--;
        _writer.WriteLine("}");
        _classInfo.ProductionContext.AddSource(
            $"{_classInfo.FullTypeName.ReplaceBraces()}MapExtensions.g.cs",
            ((StringWriter)_writer.InnerWriter).ToString()
        );
    }
}
