using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Text;
using HKW.SourceGeneratorUtils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HKW.HKWMapper.SourceGenerator;

internal class MapAttributeGenerator
{
    public static Compilation? Generate(ICollection<ClassInfo> classInfos)
    {
        var x = new MapAttributeGenerator();
        return x.Execute(classInfos);
    }

    public MapAttributeGenerator() { }

    private Compilation? Execute(ICollection<ClassInfo> classInfos)
    {
        var stringStream = new StringWriter();
        var writer = new IndentedTextWriter(stringStream);
        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("#nullable enable");
        foreach (var classInfo in classInfos)
        {
            writer.WriteLine("namespace " + classInfo.ClassSymbol.ContainingNamespace);
            writer.WriteLine("{");
            writer.Indent++;
            foreach (var mapTarget in classInfo.MapTargets)
                writer.WriteInfo(mapTarget.Attribute);
            writer.Indent--;
            writer.WriteLine("}");
        }
        // 将生成的代码添加到生成器中, 否则将无法正确识别创建的特性
        var attributeSourceText = SourceText.From(
            stringStream.ToString(),
            System.Text.Encoding.UTF8
        );
        GeneratorHelper.ProductionContext.AddSource("MapAttributes.g.cs", attributeSourceText);
        var options = ((CSharpCompilation)GeneratorHelper.Compilation).SyntaxTrees[0].Options;
        var attributeTree = CSharpSyntaxTree.ParseText(
            attributeSourceText,
            (CSharpParseOptions)options
        );
        return GeneratorHelper.Compilation.AddSyntaxTrees(attributeTree);
    }
}
