<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>Enable</ImplicitUsings>
    <Nullable>Enable</Nullable>
    <RootNamespace>HKW.HKWMapper.Demo</RootNamespace>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HKW.Mapper\HKW.Mapper.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
  </ItemGroup>
  <ItemGroup>
    <!-- 引用的包 -->
    <PackageReference Include="HKW.SourceGeneratorUtils" Version="0.1.10" PrivateAssets="all" GeneratePathProperty="true" />
    <!-- 项目分析器必须引用包, 否则 FileNotFoundException -->
    <Analyzer Include="$(PkgHKW_SourceGeneratorUtils)\lib\netstandard2.0\*.dll" />
  </ItemGroup>
</Project>
